import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../../components/Navbar";
import Footer from "../../components/Footer";
import ReactLenis from "lenis/react";
import {MouseWheelProvider} from "../../context/MouseWheelProvider";

const FiraCodeRegular = localFont({
    src: "./fonts/FiraCode-Regular.ttf",
    variable: "--font-firacode-regular",
});
const FiraCodeBold = localFont({
    src: "./fonts/FiraCode-Bold.ttf",
    variable: "--font-firacode-bold",
});
const Exo2Regular = localFont({
    src: "./fonts/Exo2-Regular.ttf",
    variable: "--font-exo2-regular",
});
const Exo2Bold = localFont({
    src: "./fonts/Exo2-Bold.ttf",
    variable: "--font-exo2-bold",
});
const AntonRegular = localFont({
    src: "./fonts/Anton-Regular.ttf",
    variable: "--font-anton-regular",
});

export const metadata = {
    title: "Nahid Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`${FiraCodeRegular.variable} ${FiraCodeBold.variable} ${Exo2Regular.variable} ${Exo2Bold.variable} ${AntonRegular.variable} bg-[#f5eee5] w-full`}
        >
        <MouseWheelProvider>
            <ReactLenis options={{duration: 2}} root>
                <div className="snap-container snap-y snap-mandatory overflow-y-scroll h-screen">
                    <Navbar/>
                    {children}
                    <Footer/>
                </div>
            </ReactLenis>
        </MouseWheelProvider>
        </body>
        </html>
    );
}
